"""empty message

Revision ID: 4301c6901586
Revises: 707b0433c84d
Create Date: 2025-01-23 12:00:08.435456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4301c6901586'
down_revision = '707b0433c84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
