"""empty message

Revision ID: 707b0433c84d
Revises: de917ff16c65
Create Date: 2025-01-23 11:41:53.320956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707b0433c84d'
down_revision = 'de917ff16c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
